sonar.projectKey=lbbs-fullstack
sonar.projectName=LBBS Fullstack
sonar.projectVersion=1.0
sonar.host.url=https://sonar.def.engr.arizona.edu/
sonar.sources=backend,frontend,.gitlab-ci.yml
sonar.sourceEncoding=UTF-8
sonar.yaml.activate=true
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.venv/**,**/__pycache__/**,**/.git/**